Slider
marinanicolai/unsplash-hooks-devPro pull request #7
Opened 2022-05-17 18:55 UTC by marinanicolai

2022-05-17 22:28 UTC, yoloOnTheBattlefield requested changes

2022-05-17 22:28 UTC, yoloOnTheBattlefield commented on src/components/ImageItem/index.js
>          src={item.urls["small"]}
item.urls.small

2022-05-17 22:28 UTC, yoloOnTheBattlefield commented on src/components/PhotoGallery/PhotoGallery.styles.js
> +`;
SavedImg, Likes and Profile have the same code, consider reusing it

2022-05-17 22:28 UTC, yoloOnTheBattlefield commented on src/components/PhotoGallery/index.js
> +  );
These two arrows, seem overkill, can you reuse the same function?

2022-05-17 22:28 UTC, yoloOnTheBattlefield commented on src/components/Slider/index.js
> +import "slick-carousel/slick/slick-theme.css";
I think it's better to import these in the main index.js file

2022-05-17 22:28 UTC, yoloOnTheBattlefield commented on src/components/Slider/index.js
> +  console.log(data);
no console

2022-05-17 22:28 UTC, yoloOnTheBattlefield commented on src/components/Slider/index.js
> +          {/* <ImageItem key={data?.[0]?.id} /> */}
no commented out code

2022-05-18 17:42 UTC, marinanicolai commented on src/components/PhotoGallery/PhotoGallery.styles.js
> +`;
I didn't finish styling the items, so it will change in the future.

2022-05-25 16:12 UTC, merged